# Numpy 

In [ ]:
# third party library must be imported and installed with pip if not already
import numpy as np # using an alias for sake of typing less when using np functions, convention to use np as alias

np.__version__  # outputs current version you are working with

'2.1.3'

In [ ]:
'''
Numpy Arrays

- fixed size arrays of data
- can only hold a single data type

- this lecture works with one and two dimensional arrays
- arrays can have as many dimensions as you want but becomes cumbersome past a 2d array to grab data and work with it
- arryas are said to be semi-mutable (cant change size but can modify elements inside)

'''

data = [1,2,3,4,5,6]
type(data)
# converting this list into a numpy array
np_arr = np.array(data) 

print(np_arr) # looks exactly like a python list without comma separators

[1 2 3 4 5 6]


In [ ]:
''' 
Properties of the numpy array
    - ndim : numebr of dimensions ( # of axes )
    - shape : size of the array for each dimension
    - size : total number of elements
    - dtype : stands for data type
'''

print(f'ndim: {np_arr.ndim}')
print(f'shape: {np_arr.shape}') #displays rows and columns since it is a 1d array will just show tuple with one value
print(f'size: {np_arr.size}') 
print(f'dtype: {np_arr.dtype}') # encoding 

ndim: 1
shape: (6,)
size: 6
dtype: int64


In [14]:
# dimensions for arrays in numpy

scalar = np.array(23) # 0 dimension array
tupl = (1,2,3)
arr = np.array(tupl) # arrays can be made out of any iterable item

matrix = np.array([[1,2,3], [4,5,6]]) # multi dimensional , array of arrays
print(matrix)
print(f'ndim: {matrix.ndim}')
print(f'shape: {matrix.shape}') 
print(f'size: {matrix.size}') 
print(f'dtype: {matrix.dtype}') 


tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(tensor) # array of arrays with arrays , becomes convaluted becomes unreadable as it grows larger and larger
print(f'ndim: {tensor.ndim}')
print(f'shape: {tensor.shape}') 
print(f'size: {tensor.size}') 
print(f'dtype: {tensor.dtype}') 



[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)
size: 12
dtype: int64


In [ ]:
# indexing into arrays
# the same as you would do in python where you specify the array you want and the item in that array
# 2d array example grabbing the 5 from the matrix variable
print(matrix[1][1]) # go to array index one grab value index 1

# changing the size is illegal but we can change this value to be something else
matrix[1][1] = 10  # since changing values is mutable we can just call the object and view the value has changed
print(matrix)

new_matrix = np.append(matrix, [7,8,9]) # returns a 1d array although matrix is a 2d array known as flattening
print(new_matrix) # the original matrix is not mutated, a brand new list is created and returned

10
[[ 1  2  3]
 [ 4 10  6]]
[ 1  2  3  4 10  6  7  8  9]


In [20]:
# concatenating
new_matrix = [[7,8,9], [10,11,12]]
concat = np.concatenate([matrix, new_matrix]) # when concatenating the arrays must be the same dimensions
# because concatenate() takes a list as an argument, the amount we can concat is arbitrary
print(concat)

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
'''
    Numpy data types 
        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex floats
        M - datetime
        m - timedelta
        S - strings
        O - object
        V - void (not the same as null) used for unknown types, placeholder

    docs found on numpy.org
'''

str_arr = np.array(range(5), dtype='S') # we can specify dimensions and dtypes we want using kwargs
print(str_arr.shape)
print(str_arr.size)
print(str_arr.dtype)
print(str_arr.ndim)

# can also cast using astype() function
str_arr.astype('f') # data type of float is created and return must be reassinged because of immutability


(5,)
5
|S1
1


array([0., 1., 2., 3., 4.], dtype=float32)

In [ ]:
# copy vs view

# copy is going to own data - data is independent to base instance
# view is going to refer to the original object

copy_arr = matrix.copy()
view_arr = matrix.view()

matrix[1][1] = 5
print(copy_arr) # the copy is the same irrelevant of the change to object
print(view_arr) # because the references are pointing to the same object the view will show the same as what its pointed at

# since view is pointing to the same object changing it changes object
view_arr[1][1] = 10
print(matrix) # matrix and view_arr pointing to same obj 

print(matrix.base) # base determines if its the original or a view, if it owns the memory None is returned as value
print(view_arr.base) # since this ref does not own the memory space a copy of the array will be output




[[ 1  2  3]
 [ 4 10  6]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 10  6]]
None
[[ 1  2  3]
 [ 4 10  6]]
