# Numpy 

In [ ]:
# third party library must be imported and installed with pip if not already
import numpy as np # using an alias for sake of typing less when using np functions, convention to use np as alias

np.__version__  # outputs current version you are working with

'2.1.3'

In [ ]:
'''
Numpy Arrays

- fixed size arrays of data
- can only hold a single data type

- this lecture works with one and two dimensional arrays
- arrays can have as many dimensions as you want but becomes cumbersome past a 2d array to grab data and work with it
- arryas are said to be semi-mutable (cant change size but can modify elements inside)

'''

data = [1,2,3,4,5,6]
type(data)
# converting this list into a numpy array
np_arr = np.array(data) 

print(np_arr) # looks exactly like a python list without comma separators

[1 2 3 4 5 6]


In [ ]:
''' 
Properties of the numpy array
    - ndim : numebr of dimensions ( # of axes )
    - shape : size of the array for each dimension
    - size : total number of elements
    - dtype : stands for data type
'''

print(f'ndim: {np_arr.ndim}')
print(f'shape: {np_arr.shape}') #displays rows and columns since it is a 1d array will just show tuple with one value
print(f'size: {np_arr.size}') 
print(f'dtype: {np_arr.dtype}') # encoding 

ndim: 1
shape: (6,)
size: 6
dtype: int64


In [14]:
# dimensions for arrays in numpy

scalar = np.array(23) # 0 dimension array
tupl = (1,2,3)
arr = np.array(tupl) # arrays can be made out of any iterable item

matrix = np.array([[1,2,3], [4,5,6]]) # multi dimensional , array of arrays
print(matrix)
print(f'ndim: {matrix.ndim}')
print(f'shape: {matrix.shape}') 
print(f'size: {matrix.size}') 
print(f'dtype: {matrix.dtype}') 


tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(tensor) # array of arrays with arrays , becomes convaluted becomes unreadable as it grows larger and larger
print(f'ndim: {tensor.ndim}')
print(f'shape: {tensor.shape}') 
print(f'size: {tensor.size}') 
print(f'dtype: {tensor.dtype}') 



[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)
size: 12
dtype: int64


In [ ]:
# indexing into arrays
# the same as you would do in python where you specify the array you want and the item in that array
# 2d array example grabbing the 5 from the matrix variable
print(matrix[1][1]) # go to array index one grab value index 1

# changing the size is illegal but we can change this value to be something else
matrix[1][1] = 10  # since changing values is mutable we can just call the object and view the value has changed
print(matrix)

new_matrix = np.append(matrix, [7,8,9]) # returns a 1d array although matrix is a 2d array known as flattening
print(new_matrix) # the original matrix is not mutated, a brand new list is created and returned

10
[[ 1  2  3]
 [ 4 10  6]]
[ 1  2  3  4 10  6  7  8  9]


In [20]:
# concatenating
new_matrix = [[7,8,9], [10,11,12]]
concat = np.concatenate([matrix, new_matrix]) # when concatenating the arrays must be the same dimensions
# because concatenate() takes a list as an argument, the amount we can concat is arbitrary
print(concat)

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
'''
    Numpy data types 
        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex floats
        M - datetime
        m - timedelta
        S - strings
        O - object
        V - void (not the same as null) used for unknown types, placeholder

    docs found on numpy.org
'''

str_arr = np.array(range(5), dtype='S') # we can specify dimensions and dtypes we want using kwargs
print(str_arr.shape)
print(str_arr.size)
print(str_arr.dtype)
print(str_arr.ndim)

# can also cast using astype() function
str_arr.astype('f') # data type of float is created and return must be reassinged because of immutability


(5,)
5
|S1
1


array([0., 1., 2., 3., 4.], dtype=float32)

In [ ]:
# copy vs view

# copy is going to own data - data is independent to base instance
# view is going to refer to the original object

copy_arr = matrix.copy()
view_arr = matrix.view()

matrix[1][1] = 5
print(copy_arr) # the copy is the same irrelevant of the change to object
print(view_arr) # because the references are pointing to the same object the view will show the same as what its pointed at

# since view is pointing to the same object changing it changes object
view_arr[1][1] = 10
print(matrix) # matrix and view_arr pointing to same obj 

print(matrix.base) # base determines if its the original or a view, if it owns the memory None is returned as value
print(view_arr.base) # since this ref does not own the memory space a copy of the array will be output




[[ 1  2  3]
 [ 4 10  6]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 10  6]]
None
[[ 1  2  3]
 [ 4 10  6]]


In [ ]:
''' 
    Other ways to create an ndarray

    ones - fills array with ones using func .ones(#rows, #cols)
    zeros - fills array with 0's same syntax as ones func
    arange - .arange(start - is inclusive, stop- exclusive, step- iterator)
    linspace - .linspace(start, stop, value) gives an array of floats with n values
'''
one_arr = np.ones((2, 4), dtype = 'i') # 2d array with lists of size 4
print(one_arr)
arange_arr = np.arange(0, 5, 2) # returns 1d array with 0,2,4 of type float
print(arange_arr)
linspace_arr = np.linspace(0,5,50) # returns array of flaots with in this case 50 values
print(linspace_arr)

[[1 1 1 1]
 [1 1 1 1]]
[0 2 4]
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [ ]:
# reshaping arrays

some_arr = np.array(range(12)) # populates the array starting from 0 up to 12 exclusive in 1d
print(some_arr)
reshape_arr = some_arr.reshape(4, 3) # reshaping the array to 4 rows 3 cols it has to be able to be reshaped rows/cols = 0
print(reshape_arr)

reshape_arr = some_arr.reshape(2,1,-1) # -1 as third param can be thought of as wildcard where numpy will 
# look at the original array and find the best way to resize it to specified row and col for a 3d array
# works as such rows/(cols * 2) must evaluate to some number if it doesnt it will raise an error
# because it cannot be reshaped, uses linear algebra formulas
# for instance an array row size 12 col size 2 => 12 / (2*2) gives 3 for third dimension
print(reshape_arr)

# using .reshape(-1) does its best to flatten multi dimensional arrays
print(reshape_arr.reshape(-1)) # flattens down to a 1d array from 3d array, new object is returned original object stays same

# reshape(-1) finds out how to reshape the array to a given set of params


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# operations on arrays in Numpy

arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

print(arr1+2) # operation is done to every element in the array, very convenient 
print(arr1*2) 

# splicing a matrix
set1 = arr1[0, :] # contains all of row index 0
set2 = arr1[1, :] # contains all of row index 1
print(set1)
print(set2)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[1 2 3]
[4 5 6]


In [89]:
# iterating through a numpy array

iter_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10, 11,12]]])

for element in iter_arr[0][0]:
    print(element, end=" ") # loops through arr index 0 and array index 0 in that array
print("\n")
# can also use nditer
for element in np.nditer(iter_arr):
    print(element, end=" ") # goes through each element throughout the arr
print("\n\nconcat with axis = 1\n")
arr1 = np.ones((2,4), dtype='i')
arr2 = np.zeros((2,4), dtype='i')

print(np.concatenate([arr1, arr2], axis=1)) # chaning axis will change the shape will have 2 rows with 8 values each
# is basically appending arr2[0][0] to arr1[0][0] and so on for the rest of the rows and cols
print("\nconcat with axis 0 which is default\n")
print(np.concatenate([arr1, arr2], axis=0)) # appends cols to the end of in this case arr1

1 2 3 

1 2 3 4 5 6 7 8 9 10 11 12 

concat with axis = 1

[[1 1 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 0]]

concat with axis 0 which is default

[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]


In [93]:
# diffferent ways to concat arrays
# vstack(), hstack(), dstack()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack((arr1, arr2))) # respective rows are added together resulting in a 1d array
print(np.vstack((arr1,arr2))) # stacked vertically since were adding a row to the array a 2 d array is made
print(np.dstack((arr1, arr2))) # each element in each array is added to a new row so in this case a 3d array will be made

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [111]:
# splitting arrays

split_arr = np.array(range(100))
print(np.array_split(split_arr, 5)) # splits the original array into 5 different arrays of equal length
#numpy will try its best to make each array equal but if it cant it will allocate values to the first indexes
print(np.array_split(split_arr, 12)) 


# searching through an array
search_arr = np.array(range(1000))
find_div_by_2 = np.where(search_arr % 2 == 0) # does op on every element, returns new array with elements that satisfy condition
print(find_div_by_2)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59]), array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79]), array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])]
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16, 17]), array([18, 19, 20, 21, 22, 23, 24, 25, 26]), array([27, 28, 29, 30, 31, 32, 33, 34, 35]), array([36, 37, 38, 39, 40, 41, 42, 43]), array([44, 45, 46, 47, 48, 49, 50, 51]), array([52, 53, 54, 55, 56, 57, 58, 59]), array([60, 61, 62, 63, 64, 65, 66, 67]), array([68, 69, 70, 71, 72, 73, 74, 75]), array([76, 77, 78, 79, 80, 81, 82, 83]), array([84, 85, 86, 87, 88, 89, 90, 91]), array([92, 93, 94, 95, 96, 97, 98, 99])]
(array([  0,   2,  

In [ ]:
# sorting and searching

unsorted_arr = [1,2,5,3,6,7,8,9,3,34,56,234,12454,362346,234]
print(np.searchsorted(unsorted_arr, 9)) # will sort array first, then return index of match provides the last match index 
# if there are multiple matched
# can also just use sort() function itself

# filtering through an array 

div_by_13 = search_arr % 13 == 0 # returns an array of booleans for matches
print(div_by_13)

# we can plug this into the original array to get the values
print(search_arr[div_by_13])
#likewise we can get all the false values using ~
print(search_arr[~div_by_13])
# we can skip the intermediary variables by just plugging in the statement directly in the brackets
print(search_arr[search_arr % 13 == 0]) # less code might be harder to read 


7
[ True False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False  True False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
  True False False False False False False False 

In [120]:
# filtering between lists

groceries = np.array(['milk', 'eggs', 'bread', 'cheese'])
prices = np.array([3.99, 4.99, 1.99, 2.99])

# numpy will match corresponding indexes with each array
# it can make this connection because these sparse arrays are of the same size
groceries[prices < 4]

# can also do conditional chaining to set variables that match a condition
prices[(prices == 1.99) | (prices == 2.99)] = 3.99 # resetting the matches to another value
print(prices) # the matches values were set since its immutable we can just call the object and see the change


[3.99 4.99 3.99 3.99]
